- hosts: localhost

  vars:
     artifactory_host: 172.31.0.42 
  tasks:
    - name: Config Maven Artifactory 
      become: yes
      become_method: sudo
      template: src=./template-setting.xml  dest=./setting.xml 

